services:
  mongo:
    image: mongo:7
    container_name: biblebot-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ../../mongo_data:/data/db
    env_file:
      - ../../.env
    environment:
      MONGO_INITDB_DATABASE: biblebot

  bot:
    build:
      context: ../..
      dockerfile: docker/dev/node/Dockerfile
    container_name: biblebot-app
    restart: unless-stopped
    env_file:
      - ../../.env
    depends_on:
      - mongo
    volumes:
      - ../../bot:/usr/src/app