version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: biblebot-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ../../mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: biblebot
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    env_file:
      - ../../.env

  bot:
    build:
      context: ../..
      dockerfile: docker/prod/node/Dockerfile
    container_name: biblebot-app
    restart: unless-stopped
    env_file:
      - ../../.env
    depends_on:
      - mongo